name: NAPE Evaluator - Release Workflow

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  id-token: write

jobs:
  release:
    uses: nape-not-another-policy-engine/nape-build-deploy-release/.github/workflows/pypi-standard-release-workflow.yaml@main
    environment: release
    with:
      pypi_url: "https://test.pypi.org/legacy/"