name: NAPE Evaluator - Release Workflow

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  release:
    uses: nape-not-another-policy-engine/nape-build-deploy-release/.github/workflows/pypi-standard-release-workflow.yaml@main
    secrets: inherit
    with:
      publish_target: "test"